stages:
  - test
  - build
  - publish
cache:
  paths:
    - vendor/ruby

Unit Test:
  tags:
    - ruby
    - kirinnee
  stage: test
  script:
    - bundle install
    - bundle exec rspec
Build:
  tags:
    - ruby
    - kirinnee
  stage: build
  script: gem build $GEM_NAME
  artifacts:
    paths:
      - ./*.gem
Publish:
  tags:
    - ruby
    - kirinnee
  stage: publish
  script: gem push $GEM_NAME-*.gem -k $API_KEY
  only:
    - /v[0-9\.]*/
  except:
    - branches